[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "leetcode"
path = "src/rs/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
