/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package leetcode

data class Input(val nums: IntArray)

class Solution {
  fun moveZeroes(nums: IntArray): Unit {
    var lastZero = 0

    for (i in 0..nums.lastIndex) {
      if (nums[i] != 0) {
        nums[lastZero] = nums[i]
        lastZero += 1
      }
    }

    for (i in lastZero..nums.lastIndex) {
      nums[i] = 0
    }
  }
}

fun main() {
  var inputs: Array<Input> = arrayOf(Input(intArrayOf(0, 1, 0, 3, 12)), Input(intArrayOf(0)))

  var solution = Solution()
  for (input in inputs) {
    var nums = input.nums
    solution.moveZeroes(nums)
    println(nums.joinToString() { it.toString() })
  }
}
